### ISSUE TITLE
get ZInstaller_editor_host to work on linux

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/bash#15]
![image](https://user-images.githubusercontent.com/6021844/28751216-4a89f292-7502-11e7-9d37-967bda363103.png)

on osx it works, 
will have to download & upload to ipfs

before finishing this make sure kristof tries this, to make sure ipfs is properly propagated

**Comment by alichaddad** [comment]
After https://github.com/Jumpscale/bash/pull/17, installer should now works on Ubuntu with the exception of only office. We tried installing the only office community server and it requires dependencies that needs configuration to work( for example setting up mysql server).
