### ISSUE TITLE
Installer has some issues on Ubuntu with the bashprofile

### ISSUE THREAD

**Issue by Virgil3** [Jumpscale/bash#21]
Installer issues on Ubuntu:

- Needs root (added instructions in readme on that)

- Ubuntu doesn't use .bash_profile (see [discussion](https://askubuntu.com/questions/121413/understanding-bashrc-and-bash-profile)). I added the workaround in the readme for now but it needs to be loaded every time.

**Comment by despiegk** [comment]
put in executorbase the behaviour that .bash_profile is there on all systems
and remove it from the run method on prefab core
