### ISSUE TITLE
fix ZDockerBuildJS9

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/bash#4]
there are issues, need to see what is blocking it

**Comment by despiegk** [comment]
following should work
```
. ~/code/jumpscale/bash/zlibs.sh
ZDockerBuildJS9
ZSSH js9
```

**Comment by maxux** [comment]
Should works since https://github.com/Jumpscale/bash/commit/3b432a35fa684696d7cf3a3b37cbc27e4347ad06
