### ISSUE TITLE
add travis job to validate building/installation

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/bash#49]
on each PR

**Comment by ahussein** [comment]
you want to build/install on each PR ?

**Comment by ahussein** [comment]
We need to enable travis on this repo. I do not have admin access to do it.

**Comment by rkhamis** [comment]
@ahussein I enabled travis. I think we should build on each PR because changes here affect installations and building

**Comment by rkhamis** [comment]
@ahussein I enabled travis. I think we should build on each PR because changes here affect installations and building
