### ISSUE TITLE
Installation from master turned to be on 9.3.0 branch for some repos

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/bash#51]
## Installation steps
export ZUTILSBRANCH=master
export JS9BRANCH=master
url="https://raw.githubusercontent.com/Jumpscale/bash/master/install.sh"
curl -s $url | bash
source /opt/code/github/jumpscale/bash/zlibs.sh
. ~/.bash_profile
ZInstall_ays9

## Result 
```
root@js9:/opt/code/github/jumpscale/core9# git branch
* 9.3.0
root@js9:/opt/code/github/jumpscale/core9# cd ../
ays9/    bash/    core9/   lib9/    prefab9/ 
root@js9:/opt/code/github/jumpscale/core9# cd ../lib9/
root@js9:/opt/code/github/jumpscale/lib9# git branch
* 9.3.0
root@js9:/opt/code/github/jumpscale/prefab9# git branch
* 9.3.0
root@js9:/opt/code/github/jumpscale/bash# git branch
* master
root@js9:/opt/code/github/jumpscale/ays9# git branch
* master

```

**Comment by alichaddad** [comment]
Installation for 9.2.0 should be from 9.2.0 branch now

**Comment by ahussein** [comment]
that is still a bug!

**Comment by rkhamis** [comment]
you want to elaborate your findings, @ahussein ?

**Comment by ahussein** [comment]
https://github.com/Jumpscale/bash/commit/8ba5248b9e3f668ea2745319db12a0bc2d643f1f

9.3.0 is hardcoded. we should be able to install from branches using the JS9BRANCH variable.

**Comment by rkhamis** [comment]
Fixed on this branch: https://github.com/Jumpscale/bash/tree/9.2.0 (will merge as soon as we release)
