### ISSUE TITLE
ZKeysLoad 9.3.0 fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/bash#55]
![screen shot 2017-11-13 at 20 44 03](https://user-images.githubusercontent.com/13795109/32745591-7243f760-c8b3-11e7-9f22-e00fd45ce9a0.png)

**Comment by rkhamis** [comment]
You value is incorrect. You're trying to load `ssh-agent -l` as your keyname, which is obviously incorrect

**Comment by yveskerwyn** [comment]
yes I see that, but I didn't specify any where `ssh-agent -l` as the name of my key, I only issued that prior to executing `ZKeysLoad`, I didn't set the `$SSHKEYNAME` value, or did I?

**Comment by rkhamis** [comment]
You must have :)
