### ISSUE TITLE
Automate 0-robot installation

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/bash#68]
It would be nice if ZInstall_js9_full to install 0-robot too.

**Comment by ahussein** [comment]
ZInstall_js9_full is ony installing js9 and it shouldnt install other packages. We will provide a ZInstall_0_robot command that will do a ZInstall_js9_full for you and then install 0-robot.
Please Note that the recommended method of installing 0-robot is using the available docker image https://hub.docker.com/r/jumpscale/0-robot/

**Comment by rkhamis** [comment]
it should be a separate function indeed @ahussein

**Comment by ahussein** [comment]
ZInstall_0_robot is now available on development branch
