### ISSUE TITLE
No module named 'zerotier'

### ISSUE THREAD

**Issue by nbabenko** [Jumpscale/bash#79]
Steps to reproduce:

ZKeysLoad

ZInstall_js9_all

ZDockerActive

ZSSH

js9

j.tools.prefab.local.network.zerotier.install()

j.tools.prefab.local.network.zerotier.start()

j.clients.zerotier.list()

In [10]: j.clients.zerotier.list()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 j.clients.zerotier.list()

/usr/lib/python3/dist-packages/js9.py in zerotier(self)
   1304         if self._zerotier is None:
   1305             # print("PROP:zerotier")
-> 1306             from JumpScale9Lib.clients.zerotier.ZerotierFactory import ZerotierFactory as ZerotierFactory
   1307             self._zerotier = ZerotierFactory()
   1308         return self._zerotier

/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerotier/ZerotierFactory.py in <module>()
     15 
     16 
---> 17 from .ZerotierClient import ZerotierClient
     18 
     19 

/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/zerotier/ZerotierClient.py in <module>()
      2 from js9 import j
      3 
----> 4 import zerotier
      5 import copy
      6 import time

ImportError: No module named 'zerotier'

----------------------

pip3 install zerotier
pip3 install ipcalc
 - solves the issue.

**Comment by rkhamis** [comment]
we do not by default install all dependencies. This is by design so jumpscale wouldn't become too huge. We assume the developer knows why they're using these sals/clients
